version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: autorizaciones
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # datos cargados

volumes:
  mysql_data:
